# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/105XYb57qedFSuwGPfvAUCH0NLEYY9-01
"""

!pip install matplotlib

import matplotlib.pyplot as plt

x=[10,20,30,40,50]
y=[10,20,30,40,50]
plt.plot(x,y)
plt.title("Line graph",color="green",fontsize=24)
plt.xlabel("no of hours studied")
plt.ylabel("Grades",rotation=0)
plt.legend("perfomance")
plt.xlim(0,50)
plt.ylim(0,50)
plt.xticks(x,labels=["student#1","student#2","student#3","student#4","student#5"])
# to display chart sometimes we need this function
plt.show()

category=["c","c++","java","php"]
likes=[34,56,23,55]
plt.bar(category,likes,color="green")
plt.xlabel("languages")
plt.ylabel("number of votes")

plt.scatter(x,y,marker='+',color="green")

#histogram
x_h=[12,13,99,15,16,40,18,19,20,21,22,90,24,25,97,27,28,29,30]
plt.hist(x_h,bins=4,color="yellow",edgecolor="black",linestyle="dashed")

!pip install seaborn

!pip install pandas

import pandas as pd

pd.DataFrame(x,y)

pd.DataFrame(x,y)

import seaborn as sns
import numpy as np

sns.set(style="white")
a=np.array([34,56,77,90,100])
sns.distplot(a,kde=True,color="g")
sns.boxplot(a)